### ISSUE TITLE
perf_hooks is missing in dependencies

### ISSUE THREAD

**Issue by Hendrik-Wallbaum-KT** [choojs/on-performance#8]
Thus whenever this package is required (say by bankai) it fails because the dependency will not be installed.

**Comment by goto-bus-stop** [comment]
perf_hooks is a builtin module as of Node 8.5, maybe we should noop in older versions where it doesn't exist?

**Comment by goto-bus-stop** [comment]
oh wait, we already sorta do. when building with bankai this should be fixed by https://github.com/choojs/on-performance/commit/55062d8ea6512539dc2037562fbe6692e8b68d3e

**Comment by Hendrik-Wallbaum-KT** [comment]
Hmm not sure I just deleted my `node_modules` and ran `npm i`. After that `bankai start` failed because it was missing the `perf_hooks` modules.

Running node v9.2.0 on a Mac.

**Comment by moszeed** [comment]
maybe its fixed now.
https://github.com/choojs/on-performance/pull/7

**Comment by HoverBaum** [comment]
Tried a fresh npm i again and still getting this error on `bankai start`. Strange is that even a `npm i perf_hooks` doesn't solve it but I guess that would be expected with it being a core module now.

Any change I just need to wait for some release somewhere to finish?

(sorry for mixing up accounts when creating the issue by the way)

**Comment by goto-bus-stop** [comment]
hmm, 1.2.1 should have fixed it, can you check that that is the version that was installed? if you had a package-lock.json it won't upgrade the version unless you do `npm update`, even if you nuked your entire node_modules

**Comment by yoshuawuyts** [comment]
@HoverBaum `perf_hooks` is a node 8+ API IIRC. Could you perhaps try @goto-bus-stop's suggestion? #7 should've indeed solved the issue ✨

**Comment by HoverBaum** [comment]
Ahh yeah seems like @goto-bus-stop s last comment is spot on. I was still on `1.2.0`.

Doing an actual update fixed it. Thanks for the help, will close the PR.
